---
kind: pipeline
name: default

steps:
- name: build
  privileged: true
  image: rancher/dapper:1.11.2
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - dapper ci

- name: build-all-binaries
  privileged: true
  image: rancher/dapper:1.11.2
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    CROSS: 1
  commands:
  - dapper build
  when:
    event: tag

- name:  stage-binaries
  image: rancher/dapper:1.11.2
  commands:
  - cp -r ./bin/* ./package/
  when:
    event: tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - build/bin/terraform-provider-rancher2_*
    - dist/artifacts/${DRONE_TAG}/*
    checksum:
    - sha256
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      include: [ refs/tags/*rc* ]

- name: github_binary_release
  image: plugins/github-release
  settings:
    files:
    - build/bin/terraform-provider-rancher2_*
    - dist/artifacts/${DRONE_TAG}/*
    checksum:
    - sha256
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
