---
kind: Namespace
apiVersion: v1
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  targetNamespace: cattle-system
  set:
    hostname: rancher.172.17.0.3.xip.io
    replicas: 1
    rancherImageTag: v2.5.0
